// frontend/src/components/ColorWheel.tsx
interface ColorWheelProps {
  baseColor?: string
  highlightAngles?: number[]
  size?: number
}

export default function ColorWheel({ baseColor = '#3366ff', highlightAngles = [], size = 240 }: ColorWheelProps) {
  const center = size / 2
  const radius = size / 2 - 20
  const innerRadius = radius * 0.55

  const segments = 360
  const segmentAngle = 360 / segments

  return (
    <svg width={size} height={size} viewBox={`0 0 ${size} ${size}`} className="drop-shadow-lg">
      {Array.from({ length: segments }, (_, i) => {
        const angle1 = (i * segmentAngle - 90) * (Math.PI / 180)
        const angle2 = ((i + 1) * segmentAngle - 90) * (Math.PI / 180)

        const x1Outer = center + radius * Math.cos(angle1)
        const y1Outer = center + radius * Math.sin(angle1)
        const x2Outer = center + radius * Math.cos(angle2)
        const y2Outer = center + radius * Math.sin(angle2)
        const x1Inner = center + innerRadius * Math.cos(angle1)
        const y1Inner = center + innerRadius * Math.sin(angle1)
        const x2Inner = center + innerRadius * Math.cos(angle2)
        const y2Inner = center + innerRadius * Math.sin(angle2)

        return (
          <path
            key={i}
            d={`M ${x1Inner} ${y1Inner} L ${x1Outer} ${y1Outer} A ${radius} ${radius} 0 0 1 ${x2Outer} ${y2Outer} L ${x2Inner} ${y2Inner} A ${innerRadius} ${innerRadius} 0 0 0 ${x1Inner} ${y1Inner}`}
            fill={`hsl(${i * segmentAngle}, 80%, 55%)`}
          />
        )
      })}

      <circle cx={center} cy={center} r={innerRadius - 2} fill="white" />

      <circle cx={center} cy={center} r={innerRadius * 0.6} fill={baseColor} className="drop-shadow-md" />

      {highlightAngles.map((angle, i) => {
        const rad = (angle - 90) * (Math.PI / 180)
        const dotRadius = (radius + innerRadius) / 2
        const x = center + dotRadius * Math.cos(rad)
        const y = center + dotRadius * Math.sin(rad)
        return (
          <g key={i}>
            <circle cx={x} cy={y} r={10} fill="white" stroke="white" strokeWidth={3} className="drop-shadow" />
            <circle cx={x} cy={y} r={7} fill={`hsl(${angle}, 80%, 55%)`} />
          </g>
        )
      })}
    </svg>
  )
}

// frontend/src/components/ColorWheel.vue
<script setup lang="ts">
withDefaults(defineProps<{
  baseColor?: string
  highlightAngles?: number[]
  size?: number
}>(), {
  baseColor: '#3366ff',
  highlightAngles: () => [],
  size: 240,
})

function polarToCart(cx: number, cy: number, r: number, angleDeg: number) {
  const rad = ((angleDeg - 90) * Math.PI) / 180
  return { x: cx + r * Math.cos(rad), y: cy + r * Math.sin(rad) }
}
</script>

<template>
  <svg :width="size" :height="size" :viewBox="`0 0 ${size} ${size}`" class="drop-shadow-lg">
    <!-- Color ring segments -->
    <path
      v-for="i in 360"
      :key="i"
      :d="(() => {
        const center = size / 2
        const radius = size / 2 - 20
        const innerRadius = radius * 0.55
        const a1 = ((i - 1) - 90) * Math.PI / 180
        const a2 = (i - 90) * Math.PI / 180
        const x1o = center + radius * Math.cos(a1)
        const y1o = center + radius * Math.sin(a1)
        const x2o = center + radius * Math.cos(a2)
        const y2o = center + radius * Math.sin(a2)
        const x1i = center + innerRadius * Math.cos(a1)
        const y1i = center + innerRadius * Math.sin(a1)
        const x2i = center + innerRadius * Math.cos(a2)
        const y2i = center + innerRadius * Math.sin(a2)
        return `M ${x1i} ${y1i} L ${x1o} ${y1o} A ${radius} ${radius} 0 0 1 ${x2o} ${y2o} L ${x2i} ${y2i} A ${innerRadius} ${innerRadius} 0 0 0 ${x1i} ${y1i}`
      })()"
      :fill="`hsl(${i - 1}, 80%, 55%)`"
    />

    <!-- Inner white circle -->
    <circle :cx="size / 2" :cy="size / 2" :r="(size / 2 - 20) * 0.55 - 2" fill="white" />

    <!-- Base color dot -->
    <circle :cx="size / 2" :cy="size / 2" :r="(size / 2 - 20) * 0.55 * 0.6" :fill="baseColor" class="drop-shadow-md" />

    <!-- Highlight dots -->
    <g v-for="(angle, idx) in highlightAngles" :key="idx">
      <circle
        :cx="polarToCart(size / 2, size / 2, ((size / 2 - 20) + (size / 2 - 20) * 0.55) / 2, angle).x"
        :cy="polarToCart(size / 2, size / 2, ((size / 2 - 20) + (size / 2 - 20) * 0.55) / 2, angle).y"
        :r="10"
        fill="white"
        stroke="white"
        :stroke-width="3"
        class="drop-shadow"
      />
      <circle
        :cx="polarToCart(size / 2, size / 2, ((size / 2 - 20) + (size / 2 - 20) * 0.55) / 2, angle).x"
        :cy="polarToCart(size / 2, size / 2, ((size / 2 - 20) + (size / 2 - 20) * 0.55) / 2, angle).y"
        :r="7"
        :fill="`hsl(${angle}, 80%, 55%)`"
      />
    </g>
  </svg>
</template>
