// frontend/src/components/common/ColorSwatch.vue
<script setup lang="ts">
import { ref } from 'vue'
import { Copy, Check } from 'lucide-vue-next'

const props = defineProps<{
  hex: string
  percentage?: number
  showInfo?: boolean
  size?: 'sm' | 'md' | 'lg'
}>()

const copied = ref(false)

async function copyHex() {
  try {
    await navigator.clipboard.writeText(props.hex)
    copied.value = true
    setTimeout(() => (copied.value = false), 1500)
  } catch {
    // fallback
  }
}

const sizeClasses = {
  sm: 'w-8 h-8 rounded',
  md: 'w-12 h-12 rounded-lg',
  lg: 'w-16 h-16 rounded-xl',
}
</script>

<template>
  <div class="flex items-center gap-3 group">
    <div
      :class="sizeClasses[size || 'md']"
      :style="{ backgroundColor: hex }"
      class="shadow-sm border border-black/10 shrink-0"
    />
    <div v-if="showInfo" class="min-w-0">
      <div class="flex items-center gap-1.5">
        <span class="text-sm font-mono font-medium" :style="{ color: 'var(--color-text)' }">
          {{ hex }}
        </span>
        <button
          @click.stop="copyHex"
          class="opacity-0 group-hover:opacity-100 transition-opacity p-0.5 rounded hover:bg-slate-100 dark:hover:bg-slate-800"
          :style="{ color: 'var(--color-text-secondary)' }"
        >
          <Check v-if="copied" class="w-3.5 h-3.5 text-green-500" />
          <Copy v-else class="w-3.5 h-3.5" />
        </button>
      </div>
      <span
        v-if="percentage !== undefined"
        class="text-xs"
        :style="{ color: 'var(--color-text-secondary)' }"
      >
        {{ percentage.toFixed(1) }}%
      </span>
    </div>
  </div>
</template>

// frontend/src/components/ColorSwatch.tsx
import { useState } from 'react'
import { Copy, Check } from 'lucide-react'
import { getContrastColor } from '../utils/color'
import type { ColorInfo } from '../types'

interface ColorSwatchProps {
  color: ColorInfo
  size?: 'sm' | 'md' | 'lg'
  showInfo?: boolean
  showPercentage?: boolean
  onClick?: () => void
}

export default function ColorSwatch({
  color,
  size = 'md',
  showInfo = true,
  showPercentage = false,
  onClick,
}: ColorSwatchProps) {
  const [copied, setCopied] = useState(false)

  const sizeClasses = {
    sm: 'h-10 w-10 rounded-lg text-[10px]',
    md: 'h-16 w-16 rounded-xl text-xs',
    lg: 'h-24 w-full rounded-xl text-sm',
  }

  const handleCopy = async (e: React.MouseEvent) => {
    e.stopPropagation()
    await navigator.clipboard.writeText(color.hex)
    setCopied(true)
    setTimeout(() => setCopied(false), 1500)
  }

  const textColor = getContrastColor(color.hex)

  return (
    <div className="flex flex-col items-center gap-1.5 group" onClick={onClick}>
      <div
        className={`${sizeClasses[size]} flex items-center justify-center cursor-pointer
                    transition-all duration-200 hover:scale-105 hover:shadow-lg relative`}
        style={{ backgroundColor: color.hex }}
      >
        <button
          onClick={handleCopy}
          className="opacity-0 group-hover:opacity-100 transition-opacity p-1 rounded"
          style={{ color: textColor }}
        >
          {copied ? <Check size={14} /> : <Copy size={14} />}
        </button>
        {showPercentage && color.percentage > 0 && (
          <span
            className="absolute bottom-1 right-1 text-[10px] font-medium px-1 rounded"
            style={{ color: textColor, backgroundColor: 'rgba(0,0,0,0.15)' }}
          >
            {color.percentage}%
          </span>
        )}
      </div>
      {showInfo && (
        <div className="text-center">
          <p className="text-xs font-mono font-medium text-surface-700 uppercase">{color.hex}</p>
          {size === 'lg' && (
            <p className="text-[10px] text-surface-500 mt-0.5">
              RGB({color.rgb.r}, {color.rgb.g}, {color.rgb.b})
            </p>
          )}
        </div>
      )}
    </div>
  )
}
